export const GroundFloorRooms = [
    {
        name: "Avadh Room",
        roomId: "001",
        // searchTags: []
        floor: 0,
        noOfBeds: 2,
        // maxCapacity: 
        coverPhoto: "/images/room-1.jpg",
        gallery: ["/images/room-1.jpg"],
        shortDescription: "",
        longDescription: "Awadh, known in British historical texts, is a historical region in northern India",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        // isSwimmingPool: false,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "delux",
        regularPrice: 10000,
        discount: 0,
        // currency: 
        // deletedAt
    },
    {
        name: "Nagaland Room",
        roomId: "002",
        floor: 0,
        noOfBeds: 2,
        coverPhoto: "/images/rooms/room6.jpg",
        gallery: ["/images/rooms/room6.jpg"],
        shortDescription: "",
        longDescription: "It's home to diverse indigenous tribes, with festivals and markets celebrating the different tribes' culture",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "delux",
        regularPrice: 10000,
        discount: 0
    },
    {
        name: "Maharashthara Room",
        roomId: "003",
        floor: 0,
        noOfBeds: 4,
        coverPhoto: "/images/room-3.jpg",
        gallery: ["/images/room-3.jpg"],
        shortDescription: "",
        longDescription: "The third largest state of india, Maharashtra occupies a significant portion of the deccan plateau",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "delux",
        regularPrice: 10000,
        discount: 0
    },
    {
        name: "Himachal Room",
        roomId: "004",
        floor: 0,
        noOfBeds: 3,
        coverPhoto: "/images/rooms/room3.jpg",
        gallery: ["/images/rooms/room3.jpg"],
        shortDescription: "",
        longDescription: "It is a hilly state in northern india lies in the lap of the the king of mountain",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "delux",
        regularPrice: 10000,
        discount: 0
    },
    {
        name: "Sikkim Room",
        roomId: "005",
        floor: 0,
        noOfBeds: 2,
        coverPhoto: "/images/room-5.jpg",
        gallery: ["/images/room-5.jpg"],
        shortDescription: "",
        longDescription: "It is a unique blend of different religion, customs and tradition of different community",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "delux",
        regularPrice: 10000,
        discount: 0
    },
    {
        name: "Bengal Room",
        roomId: "006",
        floor: 0,
        noOfBeds: 3,
        coverPhoto: "/images/rooms/room1.jpg",
        gallery: ["/images/rooms/room1.jpg"],
        shortDescription: "",
        longDescription: "It is at the eastern end of gangetic plains the apex of the bay of bengal kolkata the capital of west bengal",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "delux",
        regularPrice: 10000,
        discount: 0
    },
];

export const FirstFloorRooms = [
    {
        name: "Colonial Room",
        roomId: "101",
        // searchTags: []
        floor: 1,
        noOfBeds: 2,
        // maxCapacity: 
        coverPhoto: "/images/rooms/room1.jpg",
        gallery: ["/images/rooms/room1.jpg"],
        shortDescription: "",
        longDescription: "Awadh, known in British historical texts, is a historical region in northern India",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        // isSwimmingPool: false,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "luxury",
        regularPrice: 10000,
        discount: 0,
        // currency: 
        // deletedAt
    },
    {
        name: "Karnataka Room",
        roomId: "102",
        floor: 1,
        noOfBeds: 3,
        coverPhoto: "/images/rooms/room2.jpg",
        gallery: ["/images/rooms/room2.jpg"],
        shortDescription: "",
        longDescription: "Karnataka is a state in southwest India with Arabian Sea coastlines",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "luxury",
        regularPrice: 10000,
        discount: 0
    },
    
    {
        name: "Kashmir Room",
        roomId: "103",
        floor: 1,
        noOfBeds: 3,
        coverPhoto: "/images/rooms/room3.jpg",
        gallery: ["/images/rooms/room3.jpg"],
        shortDescription: "",
        longDescription: "The Paradise on earth.The state lies in the extreme north",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "luxury",
        regularPrice: 10000,
        discount: 0
    },
    {
        name: "Goa Room",
        roomId: "104",
        floor: 1,
        noOfBeds: 3,
        coverPhoto: "/images/rooms/room4.jpg",
        gallery: ["/images/rooms/room4.jpg"],
        shortDescription: "",
        longDescription: "Goa is a state in western India with coastlines stretching along the Arabian Sea",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "luxury",
        regularPrice: 10000,
        discount: 0
    },
    {
        name: "Sanchi Room",
        roomId: "102",
        floor: 1,
        noOfBeds: 3,
        coverPhoto: "/images/rooms/room5.jpg",
        gallery: ["/images/rooms/room5.jpg"],
        shortDescription: "",
        longDescription: "Sanchi has been bestowed with a rich legacy of buddhist",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "luxury",
        regularPrice: 10000,
        discount: 0
    },
    {
        name: "Rajasthan Room",
        roomId: "102",
        floor: 1,
        noOfBeds: 3,
        coverPhoto: "/images/rooms/room2.jpg",
        gallery: ["/images/rooms/room2.jpg"],
        shortDescription: "",
        longDescription: "Rajasthan",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "luxury",
        regularPrice: 10000,
        discount: 0
    },
    {
        name: "Rajputhana  Room",
        roomId: "106",
        floor: 1,
        noOfBeds: 3,
        coverPhoto: "/images/rooms/room6.jpg",
        gallery: ["/images/rooms/room6.jpg"],
        shortDescription: "",
        longDescription: "Karnataka",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "luxury",
        regularPrice: 10000,
        discount: 0
    },
    {
        name: "Madhubani  Room",
        roomId: "107",
        floor: 1,
        noOfBeds: 3,
        coverPhoto: "/images/rooms/room7.jpg",
        gallery: ["/images/rooms/room7.jpg"],
        shortDescription: "",
        longDescription: "Karnataka",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "luxury",
        regularPrice: 10000,
        discount: 0
    }
];

export const SecondFloorRooms = [
    {
        name: "Colonial Room",
        roomId: "201",
        // searchTags: []
        floor: 2,
        noOfBeds: 2,
        // maxCapacity: 
        coverPhoto: "/images/rooms/room1.jpg",
        gallery: ["/images/rooms/room1.jpg"],
        shortDescription: "",
        longDescription: "Awadh, known in British historical texts, is a historical region in northern India",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        // isSwimmingPool: false,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "luxury",
        regularPrice: 10000,
        discount: 0,
        // currency: 
        // deletedAt
    },
    {
        name: "Tamil nadu Room",
        roomId: "202",
        floor: 2,
        noOfBeds: 3,
        coverPhoto: "/images/rooms/room2.jpg",
        gallery: ["/images/rooms/room2.jpg"],
        shortDescription: "",
        longDescription: "Karnataka is a state in southwest India with Arabian Sea coastlines",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "luxury",
        regularPrice: 10000,
        discount: 0
    },
    
    {
        name: "Orissa Room",
        roomId: "203",
        floor: 2,
        noOfBeds: 3,
        coverPhoto: "/images/room-3.jpg",
        gallery: ["/images/room-3.jpg"],
        shortDescription: "",
        longDescription: "The Paradise on earth.The state lies in the extreme north",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "luxury",
        regularPrice: 10000,
        discount: 0
    },
    {
        name: "Assam Room",
        roomId: "204",
        floor: 2,
        noOfBeds: 3,
        coverPhoto: "/images/rooms/room4.jpg",
        gallery: ["/images/rooms/room4.jpg"],
        shortDescription: "",
        longDescription: "Goa is a state in western India with coastlines stretching along the Arabian Sea",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "luxury",
        regularPrice: 10000,
        discount: 0
    },
    {
        name: "Kerala Room",
        roomId: "205",
        floor: 2,
        noOfBeds: 3,
        coverPhoto: "/images/room-5.jpg",
        gallery: ["/images/room-5.jpg"],
        shortDescription: "",
        longDescription: "Sanchi has been bestowed with a rich legacy of buddhist",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "luxury",
        regularPrice: 10000,
        discount: 0
    },
    {
        name: "Jodhpur Room",
        roomId: "206",
        floor: 2,
        noOfBeds: 3,
        coverPhoto: "/images/rooms/room6.jpg",
        gallery: ["/images/rooms/room6.jpg"],
        shortDescription: "",
        longDescription: "Karnataka",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "luxury",
        regularPrice: 10000,
        discount: 0
    },
    {
        name: "Gujarat Room",
        roomId: "207",
        floor: 2,
        noOfBeds: 3,
        coverPhoto: "/images/rooms/room7.jpg",
        gallery: ["/images/rooms/room7.jpg"],
        shortDescription: "",
        longDescription: "Karnataka",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "luxury",
        regularPrice: 10000,
        discount: 0
    },
    {
        name: "Punjab Room",
        roomId: "202",
        floor: 2,
        noOfBeds: 3,
        coverPhoto: "/images/rooms/room2.jpg",
        gallery: ["/images/rooms/room2.jpg"],
        shortDescription: "",
        longDescription: "Karnataka",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "luxury",
        regularPrice: 10000,
        discount: 0
    },
];

export const ThirdFloorRooms = [
    {
        name: "Ganga View Room",
        roomId: "301",
        // searchTags: []
        floor: 3,
        noOfBeds: 2,
        // maxCapacity: 
        coverPhoto: "/images/rooms/room8.jpg",
        gallery: ["/images/rooms/room8.jpg"],
        shortDescription: "",
        longDescription: "With the motive to rob the golden treasury of india number of people inwaded in last five thousand year",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        // isSwimmingPool: false,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "luxury",
        regularPrice: 10000,
        discount: 0,
        // currency: 
        // deletedAt
    },
    {
        name: "Ganga View Room",
        roomId: "302",
        // searchTags: []
        floor: 3,
        noOfBeds: 2,
        // maxCapacity: 
        coverPhoto: "/images/rooms/room9.jpg",
        gallery: ["/images/rooms/room9.jpg"],
        shortDescription: "",
        longDescription: "With the motive to rob the golden treasury of india number of people inwaded in last five thousand year",
        isBreakfast: true,
        isDinner: true,
        isRiverView: false,
        isWifi: true,
        // isSwimmingPool: false,
        isTelevision: true,
        isAirConditioned: true,
        isParking: false,
        customerRating: 8,
        luxuryCategory: "luxury",
        regularPrice: 10000,
        discount: 0,
        // currency: 
        // deletedAt
    },
];